In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("laptopprice.csv")

In [17]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [18]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
818    False
819    False
820    False
821    False
822    False
Length: 823, dtype: bool

In [19]:
df.duplicated().sum()

np.int64(21)

In [20]:
df.isnull()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
819,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
820,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
821,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
822,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
df.drop_duplicates(inplace=True)

In [22]:
df.dropna

<bound method DataFrame.dropna of       brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
0      ASUS           Intel        Core i3            10th   4 GB     DDR4
1    Lenovo           Intel        Core i3            10th   4 GB     DDR4
2    Lenovo           Intel        Core i3            10th   4 GB     DDR4
3      ASUS           Intel        Core i5            10th   8 GB     DDR4
4      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
..      ...             ...            ...             ...    ...      ...
818    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
819    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
820    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
821    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
822  Lenovo             AMD        Ryzen 5            10th   8 GB     DDR4

         ssd      hdd       os  os_bit graphic_card_gb      weight  \
0       0 GB  1024 GB  Windows  64-bit            0 GB      Casual
1       0 GB  1024 GB  Windows  64-bit            0 GB      Casual
2       0 GB  1024 GB  Windows  64-bit            0 GB      Casual
3     512 GB     0 GB  Windows  32-bit            2 GB      Casual
4       0 GB   512 GB  Windows  64-bit            0 GB      Casual
..       ...      ...      ...     ...             ...         ...
818  1024 GB     0 GB  Windows  64-bit            0 GB      Casual
819  1024 GB     0 GB  Windows  64-bit            0 GB      Casual
820  1024 GB     0 GB  Windows  64-bit            4 GB      Casual
821  1024 GB     0 GB  Windows  64-bit            4 GB      Casual
822   512 GB     0 GB      DOS  64-bit            0 GB  ThinNlight

        warranty Touchscreen msoffice   Price   rating  Number of Ratings  \
0    No warranty          No       No   34649  2 stars                  3
1    No warranty          No       No   38999  3 stars                 65
2    No warranty          No       No   39999  3 stars                  8
3    No warranty          No       No   69990  3 stars                  0
4    No warranty          No       No   26990  3 stars                  0
..           ...         ...      ...     ...      ...                ...
818       1 year          No       No  135990  3 stars                  0
819       1 year          No       No  144990  3 stars                  0
820       1 year          No       No  149990  3 stars                  0
821       1 year          No       No  142990  3 stars                  0
822  No warranty          No       No   57490  4 stars                 18

     Number of Reviews
0                    0
1                    5
2                    1
3                    0
4                    0
..                 ...
818                  0
819                  0
820                  0
821                  0
822                  4

[802 rows x 19 columns]>

In [23]:
df.drop(['os','os_bit','weight','msoffice','rating','Number of Ratings','Number of Reviews'],axis=1,inplace=True)

In [24]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [25]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [26]:
brand_dict={'ASUS':1, 'Lenovo':2, 'acer':3, 'Avita':4, 'HP':5, 'DELL':6, 'MSI':7, 'APPLE':8}

In [27]:
df['brand']=df['brand'].map(brand_dict)

In [ ]:
df

In [28]:
df['brand'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [30]:
df['processor_brand'].unique()

array(['Intel', 'AMD', 'M1'], dtype=object)

In [31]:
proc_brand_dict={'Intel':1, 'AMD':2, 'M1':3}

In [32]:
df['processor_brand']=df['processor_brand'].map(proc_brand_dict)

In [33]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [34]:
df['processor_gnrtn'].unique()

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [35]:
proc_gen_dict={'10th':1, 'Not Available':2, '11th':3, '7th':4, '8th':5, '9th':6, '4th':7,
       '12th':8}

In [37]:
df['processor_gnrtn']=df['processor_gnrtn'].map(proc_gen_dict)

In [38]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,NaN,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,Core i3,NaN,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,Core i3,NaN,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,Core i5,NaN,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,Celeron Dual,NaN,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,NaN,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,Ryzen 9,NaN,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,Ryzen 9,NaN,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,Ryzen 9,NaN,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,Ryzen 5,NaN,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [39]:
df.dtypes

brand                int64
processor_brand      int64
processor_name      object
processor_gnrtn    float64
ram_gb              object
ram_type            object
ssd                 object
hdd                 object
graphic_card_gb     object
warranty            object
Touchscreen         object
Price                int64
dtype: object

In [40]:
df['ram_gb'].unique()

array(['4 GB', '8 GB', '16 GB', '32 GB'], dtype=object)

In [41]:
ram_gb_dict={'4 GB':4, '8 GB':8, '16 GB':16, '32 GB':32}

In [42]:
df['ram_gb']=df['ram_gb'].map(ram_gb_dict)

In [43]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,NaN,4,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,Core i3,NaN,4,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,Core i3,NaN,4,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,Core i5,NaN,8,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,Celeron Dual,NaN,4,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,NaN,4,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,Ryzen 9,NaN,4,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,Ryzen 9,NaN,4,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,Ryzen 9,NaN,4,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,Ryzen 5,NaN,8,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [44]:
df['ram_type'].unique()

array(['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3'],
      dtype=object)

In [45]:
ram_type_dict={'DDR4':1, 'LPDDR4':2, 'LPDDR4X':3, 'DDR5':4, 'DDR3':5, 'LPDDR3':6}

In [46]:
df['ram_type']=df['ram_type'].map(ram_type_dict)

In [47]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,NaN,4,1,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,Core i3,NaN,4,1,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,Core i3,NaN,4,1,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,Core i5,NaN,8,1,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,Celeron Dual,NaN,4,1,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,NaN,4,1,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,Ryzen 9,NaN,4,1,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,Ryzen 9,NaN,4,1,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,Ryzen 9,NaN,4,1,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,Ryzen 5,NaN,8,1,512 GB,0 GB,0 GB,No warranty,No,57490

In [48]:
df['ssd'].unique()

array(['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB',
       '3072 GB'], dtype=object)

In [49]:
ssd_dict={'0 GB':0, '512 GB':512,'256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':2048,
       '3072 GB':3072}

In [50]:
df['ssd']=df['ssd'].map(ssd_dict)

In [51]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,NaN,4,1,0,1024 GB,0 GB,No warranty,No,34649
1,2,1,Core i3,NaN,4,1,0,1024 GB,0 GB,No warranty,No,38999
2,2,1,Core i3,NaN,4,1,0,1024 GB,0 GB,No warranty,No,39999
3,1,1,Core i5,NaN,8,1,512,0 GB,2 GB,No warranty,No,69990
4,1,1,Celeron Dual,NaN,4,1,0,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,NaN,4,1,1024,0 GB,0 GB,1 year,No,135990
819,1,2,Ryzen 9,NaN,4,1,1024,0 GB,0 GB,1 year,No,144990
820,1,2,Ryzen 9,NaN,4,1,1024,0 GB,4 GB,1 year,No,149990
821,1,2,Ryzen 9,NaN,4,1,1024,0 GB,4 GB,1 year,No,142990
822,2,2,Ryzen 5,NaN,8,1,512,0 GB,0 GB,No warranty,No,57490

In [52]:
df['hdd'].unique()

array(['1024 GB', '0 GB', '512 GB', '2048 GB'], dtype=object)

In [53]:
hdd_dict={'1024 GB':1024, '0 GB':0, '512 GB':512, '2048 GB':2048}

In [54]:
df['hdd']=df['hdd'].map(hdd_dict)

In [55]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,NaN,4,1,0,1024,0 GB,No warranty,No,34649
1,2,1,Core i3,NaN,4,1,0,1024,0 GB,No warranty,No,38999
2,2,1,Core i3,NaN,4,1,0,1024,0 GB,No warranty,No,39999
3,1,1,Core i5,NaN,8,1,512,0,2 GB,No warranty,No,69990
4,1,1,Celeron Dual,NaN,4,1,0,512,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,NaN,4,1,1024,0,0 GB,1 year,No,135990
819,1,2,Ryzen 9,NaN,4,1,1024,0,0 GB,1 year,No,144990
820,1,2,Ryzen 9,NaN,4,1,1024,0,4 GB,1 year,No,149990
821,1,2,Ryzen 9,NaN,4,1,1024,0,4 GB,1 year,No,142990
822,2,2,Ryzen 5,NaN,8,1,512,0,0 GB,No warranty,No,57490

In [56]:
df['graphic_card_gb'].unique()

array(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'], dtype=object)

In [57]:
graphic_card_dict={'0 GB':0, '2 GB':2, '4 GB':4, '6 GB':6, '8 GB':8}

In [58]:
df['graphic_card_gb']=df['graphic_card_gb'].map(graphic_card_dict)

In [59]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,NaN,4,1,0,1024,0,No warranty,No,34649
1,2,1,Core i3,NaN,4,1,0,1024,0,No warranty,No,38999
2,2,1,Core i3,NaN,4,1,0,1024,0,No warranty,No,39999
3,1,1,Core i5,NaN,8,1,512,0,2,No warranty,No,69990
4,1,1,Celeron Dual,NaN,4,1,0,512,0,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,NaN,4,1,1024,0,0,1 year,No,135990
819,1,2,Ryzen 9,NaN,4,1,1024,0,0,1 year,No,144990
820,1,2,Ryzen 9,NaN,4,1,1024,0,4,1 year,No,149990
821,1,2,Ryzen 9,NaN,4,1,1024,0,4,1 year,No,142990
822,2,2,Ryzen 5,NaN,8,1,512,0,0,No warranty,No,57490

In [60]:
df['warranty'].unique()

array(['No warranty', '1 year', '2 years', '3 years'], dtype=object)

In [61]:
warranty_dict={'No warranty':1, '1 year':2, '2 years':3, '3 years':4}

In [62]:
df['warranty']=df['warranty'].map(warranty_dict)

In [63]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,NaN,4,1,0,1024,0,1,No,34649
1,2,1,Core i3,NaN,4,1,0,1024,0,1,No,38999
2,2,1,Core i3,NaN,4,1,0,1024,0,1,No,39999
3,1,1,Core i5,NaN,8,1,512,0,2,1,No,69990
4,1,1,Celeron Dual,NaN,4,1,0,512,0,1,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,NaN,4,1,1024,0,0,2,No,135990
819,1,2,Ryzen 9,NaN,4,1,1024,0,0,2,No,144990
820,1,2,Ryzen 9,NaN,4,1,1024,0,4,2,No,149990
821,1,2,Ryzen 9,NaN,4,1,1024,0,4,2,No,142990
822,2,2,Ryzen 5,NaN,8,1,512,0,0,1,No,57490

In [64]:
df['Touchscreen'].unique()

array(['No', 'Yes'], dtype=object)

In [65]:
touchscreen_dict={'No':1, 'Yes':2}

In [66]:
df['Touchscreen']=df['Touchscreen'].map(touchscreen_dict)

In [67]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,NaN,4,1,0,1024,0,1,1,34649
1,2,1,Core i3,NaN,4,1,0,1024,0,1,1,38999
2,2,1,Core i3,NaN,4,1,0,1024,0,1,1,39999
3,1,1,Core i5,NaN,8,1,512,0,2,1,1,69990
4,1,1,Celeron Dual,NaN,4,1,0,512,0,1,1,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,NaN,4,1,1024,0,0,2,1,135990
819,1,2,Ryzen 9,NaN,4,1,1024,0,0,2,1,144990
820,1,2,Ryzen 9,NaN,4,1,1024,0,4,2,1,149990
821,1,2,Ryzen 9,NaN,4,1,1024,0,4,2,1,142990
822,2,2,Ryzen 5,NaN,8,1,512,0,0,1,1,57490